pipeline {
    agent any
    tools {
        jdk 'jdk'
        nodejs 'node18'
    }
    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout from Git') {
            steps {
                git branch: 'main', url: 'https://github.com/arulmurugan001/devopsprojectprime.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                    sh "npm install"
            }
        }

        stage('Docker Build & Push') {
            steps {
                script {
                    withDockerRegistry(credentialsId: 'docker', toolName: 'docker') {
                        sh '''
                            docker build -t amazon-prime-video .
                            docker tag amazon-prime-video arulmurugan786/amazon-prime-video:latest
                            docker push arulmurugan786/amazon-prime-video:latest
                        '''
                    }
                }
            }
        }

        stage('Trivy Image Scan') {
            steps {
                sh "trivy image arulmurugan786/amazon-prime-video:latest > trivyimage.txt"
            }
        }
        
       stage('deploy to kubernetes') {
            steps {
                dir('k8s'){
                script
                {
                withCredentials([file(credentialsId: 'kubeconfig-file', variable: 'KUBECONFIG')]) {
                    sh '''
                        kubectl get nodes
                        kubectl apply -f manifest.yml
                        '''
        }
    }
  }
}
}
}
    post {
        always {
            script {
                def buildStatus = currentBuild.currentResult
                def buildUser = currentBuild.getBuildCauses('hudson.model.Cause$UserIdCause')[0]?.userId ?: 'GitHub Trigger'

                emailext(
                    subject: "Pipeline ${buildStatus}: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                    body: """
                        <p><b>Jenkins CI/CD Pipeline Report</b></p>
                        <p>Project: ${env.JOB_NAME}</p>
                        <p>Build Number: ${env.BUILD_NUMBER}</p>
                        <p>Status: <b>${buildStatus}</b></p>
                        <p>Triggered By: ${buildUser}</p>
                        <p><a href="${env.BUILD_URL}">View Build Details</a></p>
                    """,
                    to: 'muruganarul1993@gmail.com',
                    from: 'muruganarul1993@gmail.com',
                    replyTo: 'muruganarul1993@gmail.com',
                    mimeType: 'text/html',
                    attachmentsPattern: 'trivy*.txt'
                )
            }
        }
    }
}
