#deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-prime-video-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amazon-prime-video
  template:
    metadata:
      labels:
        app: amazon-prime-video
    spec:
      containers:
        - name: amazon-prime-video
          image: arulmurugan786/amazon-prime-video:latest
          ports:
            - containerPort: 3000
