#service.yaml
apiVersion: v1
kind: Service
metadata:
  name: amazon-prime-video-service
spec:
  selector:
    app: amazon-prime-video
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
